routes/web.php
Route::group(['prefix' => config('admin.prefix'), 'middleware'=>'notAdmin'], function (){
    Route::get('login', 'Admin\AuthController@login')->name('admin.login');
    Route::post('login', 'Admin\AuthController@attemptLogin');
    Route::get('password/reset', 'Admin\AuthController@reset')->name('admin.password.reset');
    Route::post('password/reset', 'Admin\AuthController@attemptReset');
    Route::get('password/recover/{email}/{token}', 'Admin\AuthController@recover')->where(['email'=>'[^\/]+', 'token'=>'[^\/]+'])->name('admin.password.recover');
    Route::post('password/recover/{email}/{token}', 'Admin\AuthController@attemptRecover')->where(['email'=>'[^\/]+', 'token'=>'[^\/]+']);
});
//endregion
Route::get('verify-email/{email}/{token}', 'Site\Auth\RegisterController@verifyEmail')->name('verify_email');

Route::middleware('setLocale')->group(function(){
    Route::post('send-mail', 'Site\AppController@sendMail')->name('contacts.send_mail');
});
Route::group(['prefix' => config('admin.prefix'), 'middleware' => 'admin'], function () {
    //region CKFinder
    Route::any('file_browser/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
    Route::any('file_browser/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');
    //endregion
    Route::name('admin.')->namespace('Admin')->group(function(){
        //region Logout
        Route::post('logout', 'AuthController@logout')->name('logout');
        //endregion
        //region Home Page Redirect
        Route::get('/', 'AuthController@redirectIfAuthenticated');
        //endregion
        //region Dashboard
        Route::get('dashboard', 'DashboardController@main')->name('dashboard');
        //endregion
        //region Languages
        Route::prefix('languages')->name('languages.')->group(function() { $c='LanguagesController@';
            Route::get('', $c.'main')->name('main');
            Route::patch('', $c.'editLanguage');
        });
        //endregion
        //region Pages
        Route::prefix('pages')->name('pages.')->group(function() { $c='PagesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'addPage')->name('add');
            Route::put('add', $c.'addPage_put');
            Route::get('edit/{id}', $c.'editPage')->name('edit');
            Route::patch('edit/{id}', $c.'editPage_patch');
            Route::delete('delete', $c.'deletePage_delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Pages
        Route::prefix('new_buildings')->name('new_buildings.')->group(function() { $c='NewBuildingController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
            Route::post('search', $c.'search_estate')->middleware('ajax')->name('search_estate');
        });
        //endregion
        //region Banners
        Route::match(['get', 'post'], 'banners/{page}', 'BannersController@renderPage')->name('banners');

        Route::prefix('gallery')->group(function(){ $c='GalleriesController@';
            Route::get('{gallery}/{id?}{key?}', $c.'show')->name('gallery');
            Route::put('add', $c.'add')->name('gallery.add');
            Route::patch('edit', $c.'edit')->middleware('ajax')->name('gallery.edit');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('gallery.sort');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('gallery.delete');
            Route::post('poster', $c.'poster')->middleware('ajax')->name('gallery.poster');
        });
        //endregion
        //region Users
        Route::prefix('users')->name('users.')->group(function(){ $c='UsersController@';
            Route::get('', $c.'main')->name('main');
            Route::get('{id}', $c.'view')->name('view');
            Route::get('list/{user_type}', $c.'list')->name('list');
            Route::patch('toggle-active', $c.'toggleActive')->name('toggleActive');
        });
        //endregion
        //region Video Galleries
        Route::prefix('video-gallery')->group(function(){ $c='VideoGalleriesController@';
            Route::get('{gallery}/{id?}', $c.'show')->name('video_gallery');
            Route::get('{gallery}/add/{id?}', $c.'add')->name('video_gallery.add');
            Route::put('{gallery}/add/{id?}', $c.'add_put');
            Route::get('{id}/edit', $c.'edit')->name('video_gallery.edit');
            Route::patch('{id}/edit', $c.'edit_patch');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('video_gallery.sort');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('video_gallery.delete');
        });
        //endregion
        //region Profile
        Route::prefix('profile')->name('profile.')->group(function() { $c = 'ProfileController@';
            Route::get('', $c.'main')->name('main');
            Route::patch('', $c.'patch');
        });
        //endregion
        //region Translations
        Route::prefix('translations')->name('translations.')->group(function() { $c = 'TranslationsController@';
            Route::get('{locale}', $c.'main')->name('main');
            Route::get('{locale}/{filename}', $c.'edit')->name('edit');
            Route::patch('{locale}/{filename}', $c.'edit_patch')->name('edit');
        });
        //endregion
        //Home Page Sliders
        Route::prefix('main-slider')->name('main_slider.')->group(function() { $c='MainSliderController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //end sliders
        //region types
        Route::prefix('types')->name('types.')->group(function() { $c='TypesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Categories
        Route::prefix('categories')->name('categories.')->group(function() { $c='CategoriesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        // region Announcements
        Route::prefix('announcements')->name('announcements.')->group(function() { $c='AnnouncementsController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::get('changeStatus/{id}/{status}', $c.'changeStatus')->name('changeStatus');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Filters
        Route::prefix('filters')->name('filters.')->group(function() { $c='FiltersController@';
            Route::get('', $c.'main')->name('main');
            Route::get('priceFilters', $c.'price_filters')->name('list');
            Route::get('add/{price_filter?}/{relation?}', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}/{price_filter?}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Locations
        Route::prefix('locations')->name('locations.')->group(function() { $c='LocationsController@';
            Route::get('main/{parent_id?}/{deep?}', $c.'main')->name('main');
            Route::get('{parent_id?}/{deep?}/add', $c.'add')->name('add');
            Route::put('{parent_id?}/{deep?}/add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::post('changeLocationName', $c.'changeLocationName')->name('changeLocationName');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Estates
        Route::prefix('estates')->name('estates.')->group(function() { $c='EstatesController@';

app/Models/Banner.php
<?php

namespace App\Models;

use App\Services\Banners\BannerModel;
use App\Services\Banners\BannerData;
use App\Services\Notify\Facades\Notify;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Banner extends Model
{
    public $timestamps = false;
    public static function cacheKey($page) {
        return 'banners_'.$page;
    }
    public static function get($page) {
        $cacheKey = self::cacheKey($page);
        if (Cache::has($cacheKey)) return Cache::get($cacheKey);
        $items = self::select('key', 'data')->where('page', $page)->sort()->get()->mapToGroups(function($item){
            return [$item['key']=> new BannerData($item['data'])];
        })->toArray();
        if (!empty($items)) {
            $result = [];
            foreach ($items as $key => $item) {
                $result[$key] = new BannerModel($item);
            }
            $result = (object) $result;
            Cache::forever($cacheKey, $result);
            return $result;
        }
        return null;

    }
    public static function getBanners($page){
        return self::select('id', 'key', 'data')->where('page', $page)->sort()->get()->mapToGroups(function($item){
            return [
                $item['key']=>[
                    'id'=>$item['id'],
                    'data'=>json_decode($item['data'], true),
                ]
            ];
        });
    }

    public static function fixBanners($settings) {
        $pages = [];
        $allIds = [];
        foreach($settings as $page=>$keys) {
            $pages[] = $page;
            Cache::forget(self::cacheKey($page));
            $allKeys = [];
            foreach($keys as $key=>$data) {
                $allKeys[]=$key;
                $count = $data['count']??1;
                $ids = self::select('id')->where(['page'=>$pages, 'key'=>$key])->sort()->pluck('id')->toArray();
                $allIds = array_merge($allIds, array_slice($ids, $count));
            }
            self::where('page', $page)->whereNotIn('key', $allKeys)->delete();
        }
        self::whereNotIn('page', $pages)->orWhere(function($q) use ($allIds){
            $q->whereIn('id', $allIds);
        })->delete();
        return true;
    }

    public static function updateBanner($page, $key, $data, $id){
        if($id) return self::where(['id'=>$id])->update(['data'=>json($data)]);
        else return self::insert([
            'page'=>$page,
            'key'=>$key,
            'data'=>json($data),
        ]);
    }

    public function scopeSort($q) {
        return $q->orderBy('id', 'asc');
    }
}

resources/views/admin/pages/banners/about.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент страницы о компании')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>'Загаловок'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Загаловок'])
            @banner('header.title', 'Надпись блока')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('header.image', 'Изоброжение (рек шир. 1920)')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>'Контент'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('content.title', 'Название')
            @banner('content.desc', 'Текст')
            @endcard

            @card(['title'=>'Цифры'])
            @banner('content.counter1', 'Первая цифра')
            @banner('content.counter1_text', 'Подпись первой цифры')
            @banner('content.counter2', 'Вторая цифра')
            @banner('content.counter2_text', 'Подпись второй цифры')
            @banner('content.counter3', 'Третья цифра')
            @banner('content.counter3_text', 'Подпись третей цифры')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('content.image', 'Изоброжение (16:9(мин. 800))')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>'Блок после слайдера'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Надпись блока'])
            @banner('content.after_slider', 'Надпись')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('content.after_image', 'Изоброжение (16:9(мин. 800))')
            @endcard
        </div>
    </div>

    @endbannerBlock
@endsection

resources/views/admin/pages/banners/contact.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент страницы контакта')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>'Контент'])
        <div class="row">
            <div class="col-12 col-dxl-6">
                @card(['title'=>'Блок'])
                @banner('content.title', 'Название блока')
                @banner('content.text', 'Текст после названии')
                @endcard
            </div>
            <div class="col-12 col-dxl-6">
                @card(['title'=>'Блок'])
                @banner('content.image', 'Изображение блока')
                @endcard
            </div>
            <div class="col-12 col-dxl-6">
                @card(['title'=>'Блок'])
                @banner('content.email_text', 'Надпись блока письма')
                @banner('content.email_desc', 'Текст блока письма')
                @endcard
            </div>
            <div class="col-12 col-dxl-6">
                @card(['title'=>'Блок'])
                @banner('content.address_text', 'Надпись блока адреса')
                @banner('content.address_desc1', '1-ый Текст блока адреса')
                @banner('content.address_desc2', '2-ой Текст блока адреса')
                @endcard
            </div>
        </div>
    @endbannerBlock
@endsection

resources/views/admin/pages/banners/home.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент главной страницы')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>"Банер 'Поиска'"])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('search.title', 'Название')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('search.image', 'Изоброжение (16:9(мин. 1920x))')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>"Банер 'Наши сервисы'"])
    <div class="row">
        <div class="col-12">
            @cards(['title'=>'Сервисы', 'banners'=>'services'])
           <div class="row">
               <div class="col-12 col-dxl-6">
                   @banner('line1', 'Линия 1')
                   @banner('line2', 'Линия 2')
                   @banner('url', 'Ссылка')
               </div>
               <div class="col-12 col-dxl-6">
                   @banner('image', 'Изображение')
                   @banner('img_alt', 'Alt Изображения')
                   @banner('img_title', 'Title Изображения')
               </div>
           </div>
            @endcards
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>"Банер 'Бесплатные объявления'"])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('adv_title.title', 'Надпись блока')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @cards(['title'=>'Номера телефонов', 'banners'=>'adv'])
            @banner('title', 'Текст номера')
            @banner('phone', 'Номер телефона')
            @endcards
        </div>
    </div>
    @endbannerBlock

    @bannerBlock(['title'=>"Банер 'О нас'"])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('about.title', 'Название блока')
            @banner('about.desc', 'Описание блока')
            @banner('about.button_text', 'Надпись кнопки')
            @banner('about.url', 'Ссылка кнопки')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжении'])
            @banner('about.image', 'Изоброжение фона (16:9(мин. 1440 x))')
            @banner('about.image2', 'Изоброжение правого блока (2:1(мин. 360 x 180))')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>"Банер 'Наше приложение'"])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('app.title', 'Название блока')
            @banner('app.desc', 'Описание блока')
            @banner('app.url1', 'Ссылка первой кнопки')
            @banner('app.url2', 'Ссылка второй кнопки')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжении'])
            @banner('app.image', 'Изоброжение правого блока (2:1(мин. 360 x 180))')
            @banner('app.img_alt', 'Alt Изображения')
            @banner('app.img_title', 'Title Изображения')
            @banner('app.button_img1', 'Изображение первой кнопки (мин. 200х60)')
            @banner('app.button_img2', 'Изображение второй кнопки (мин. 200х60)')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>"Банер 'Новости'"])
    <div class="card">
        <div class="card-body">
            @banner('news.title', 'Загаловок блока')
        </div>
    </div>
    @endbannerBlock
@endsection

resources/views/admin/pages/banners/info.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Информация')
@section('body')
    @bannerBlock(['title'=>'Контакты'])
        <div class="row">
            <div class="col-12 col-dxl-6">
                @cards(['title'=>'Эл. почты', 'banners'=>'contacts', 'id'=>2])
                    @banner('email', 'Эл. почта')
                @endcards
                @cards(['title'=>'Эл. почта для отправки письма', 'banners'=>'contact_email'])
                    @banner('email', 'Эл. почта')
                @endcards
            </div>
            <div class="col-12 col-dxl-6">
                @cards(['title'=>'Телефоны', 'banners'=>'contacts'])
                    @banner('phone', 'Телефон')
                @endcards
                @cards(['title'=>'Адреса', 'banners'=>'contacts', 'id'=>3])
                    @banner('address', 'Адрес')
                @endcards
            </div>
            <div class="col-12 col-dxl-6">
                @cards(['title'=>'Ссылки социальных сетей', 'banners'=>'socials'])
                @banner('icon', 'Икона (20x20)')
                @banner('title', 'Название')
                @banner('url', 'Ссылка')
                @endcards
            </div>
            <div class="col-12 col-dxl-6">
                @cards(['title'=>'Альернативные ссылки футера', 'banners'=>'footer_links'])
                @banner('title', 'Название')
                @banner('url', 'Ссылка')
                @endcards
                @card(['title'=>'Карта'])
                @banner('map.source', 'Ссылка на карту')
                @endcard
            </div>
        </div>
    @endbannerBlock
    @bannerBlock(['title'=>'Контент страниц'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Блок поиска'])
            @banner('search.title', 'Напдись')
            @banner('search.desc', 'Текст под надписем')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изображение'])
            @banner('search.image', 'Изображение')
            @endcard
        </div>
        <div class="col-12 ">
            @cards(['title'=>'Блок страницы поиска', 'banners'=>'search_page'])
            <div class="row">
                <div class="col-12 col-dxl-6">
                    @banner('title', 'Напдись')
                    @banner('url', 'Ссылка')
                </div>
                <div class="col-12 col-dxl-6">
                    @banner('image', 'Изображение')
                </div>
            </div>
            @endcards
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Логотипы'])
            @banner('data.header_logo', 'Верхний логотип (шир. <=260)')
            @banner('data.menu_logo', 'Нижний логотип (шир. <=260)')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'SEO'])
            @banner('seo.title_suffix', 'Суффикс названии')
            @endcard
        </div>
    </div>
    @endbannerBlock
@endsection

resources/views/admin/pages/banners/layout.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="banner-page">
        <form action="{{ url()->current() }}" method="post" enctype="multipart/form-data">
            @csrf
            @yield('body')
            <div class="col-12 save-btn-fixed"><button type="submit"></button></div>
        </form>
    </div>
@endsection
@push('js')
    @ckeditor
    @js(aApp('minicolors/jquery.minicolors.js'))
    @js(aApp('datepicker/datepicker.js'))
@endpush
@push('css')
    @css(aApp('minicolors/jquery.minicolors.css'))
    @css(aApp('datepicker/datepicker.css'))
@endpush

resources/views/admin/pages/banners/menu.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Баннеры')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    <div class="row">
        <div class="col-12 col-dxl-6">
            @bannerBlock(['title'=>'Контент'])
                @card(['title' => 'Блок "Другие продукты"'])
                    @banner('data.other_products', 'Название блока')
                @endcard
            @endbannerBlock
        </div>
    </div>
@endsection

resources/views/admin/pages/banners/news.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент страницы сервисов')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>'Загаловок'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Загаловок'])
            @banner('header.title', 'Надпись блока')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('header.image', 'Изоброжение (рек шир. 1920)')
            @endcard
        </div>
    </div>
    @endbannerBlock
@endsection

resources/views/admin/pages/banners/partners.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент страницы сотрудников')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>'Загаловок'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Загаловок'])
            @banner('content.title', 'Надпись блока')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('content.image', 'Изоброжение (рек шир. 1920)')
            @endcard
        </div>
    </div>
    @endbannerBlock
@endsection

resources/views/admin/pages/banners/projects.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент страницы о проекте')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>'Загаловок'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Загаловок'])
            @banner('header.title', 'Надпись блока')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('header.image', 'Изоброжение (рек шир. 1920)')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>'Контент'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('content.title', 'Загаловок')
            @banner('content.desc', 'Текст')
            @endcard
        </div>

    </div>
    @endbannerBlock
@endsection

resources/views/admin/pages/banners/services.blade.php
@extends('admin.pages.banners.layout')
@section('title', 'Контент страницы сервисов')
@php $back_url = route('admin.pages.main') @endphp
@section('body')
    @bannerBlock(['title'=>'Загаловок'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('header.image', 'Изоброжение (рек шир. 1440)')
            @endcard
        </div>
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Изоброжение'])
            @banner('header.image2', 'Логотип на Изоброжении (рек шир. x200)')
            @endcard
        </div>
    </div>
    @endbannerBlock
    @bannerBlock(['title'=>'Контент'])
    <div class="row">
        <div class="col-12 col-dxl-6">
            @card(['title'=>'Контент'])
            @banner('content.title', 'Загаловок')
            @banner('content.desc', 'Описание')
            @endcard
        </div>
    </div>
    @endbannerBlock
@endsection