routes/web.php
    Route::post('login', 'Admin\AuthController@attemptLogin');
    Route::get('password/reset', 'Admin\AuthController@reset')->name('admin.password.reset');
    Route::post('password/reset', 'Admin\AuthController@attemptReset');
    Route::get('password/recover/{email}/{token}', 'Admin\AuthController@recover')->where(['email'=>'[^\/]+', 'token'=>'[^\/]+'])->name('admin.password.recover');
    Route::post('password/recover/{email}/{token}', 'Admin\AuthController@attemptRecover')->where(['email'=>'[^\/]+', 'token'=>'[^\/]+']);
});
//endregion
Route::get('verify-email/{email}/{token}', 'Site\Auth\RegisterController@verifyEmail')->name('verify_email');

Route::middleware('setLocale')->group(function(){
    Route::post('send-mail', 'Site\AppController@sendMail')->name('contacts.send_mail');
});
Route::group(['prefix' => config('admin.prefix'), 'middleware' => 'admin'], function () {
    //region CKFinder
    Route::any('file_browser/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
    Route::any('file_browser/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');
    //endregion
    Route::name('admin.')->namespace('Admin')->group(function(){
        //region Logout
        Route::post('logout', 'AuthController@logout')->name('logout');
        //endregion
        //region Home Page Redirect
        Route::get('/', 'AuthController@redirectIfAuthenticated');
        //endregion
        //region Dashboard
        Route::get('dashboard', 'DashboardController@main')->name('dashboard');
        //endregion
        //region Languages
        Route::prefix('languages')->name('languages.')->group(function() { $c='LanguagesController@';
            Route::get('', $c.'main')->name('main');
            Route::patch('', $c.'editLanguage');
        });
        //endregion
        //region Pages
        Route::prefix('pages')->name('pages.')->group(function() { $c='PagesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'addPage')->name('add');
            Route::put('add', $c.'addPage_put');
            Route::get('edit/{id}', $c.'editPage')->name('edit');
            Route::patch('edit/{id}', $c.'editPage_patch');
            Route::delete('delete', $c.'deletePage_delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Pages
        Route::prefix('new_buildings')->name('new_buildings.')->group(function() { $c='NewBuildingController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
            Route::post('search', $c.'search_estate')->middleware('ajax')->name('search_estate');
        });
        //endregion
        //region Banners
        Route::match(['get', 'post'], 'banners/{page}', 'BannersController@renderPage')->name('banners');

        Route::prefix('gallery')->group(function(){ $c='GalleriesController@';
            Route::get('{gallery}/{id?}{key?}', $c.'show')->name('gallery');
            Route::put('add', $c.'add')->name('gallery.add');
            Route::patch('edit', $c.'edit')->middleware('ajax')->name('gallery.edit');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('gallery.sort');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('gallery.delete');
            Route::post('poster', $c.'poster')->middleware('ajax')->name('gallery.poster');
        });
        //endregion
        //region Users
        Route::prefix('users')->name('users.')->group(function(){ $c='UsersController@';
            Route::get('', $c.'main')->name('main');
            Route::get('{id}', $c.'view')->name('view');
            Route::get('list/{user_type}', $c.'list')->name('list');
            Route::patch('toggle-active', $c.'toggleActive')->name('toggleActive');
        });
        //endregion
        //region Video Galleries
        Route::prefix('video-gallery')->group(function(){ $c='VideoGalleriesController@';
            Route::get('{gallery}/{id?}', $c.'show')->name('video_gallery');
            Route::get('{gallery}/add/{id?}', $c.'add')->name('video_gallery.add');
            Route::put('{gallery}/add/{id?}', $c.'add_put');
            Route::get('{id}/edit', $c.'edit')->name('video_gallery.edit');
            Route::patch('{id}/edit', $c.'edit_patch');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('video_gallery.sort');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('video_gallery.delete');
        });
        //endregion
        //region Profile
        Route::prefix('profile')->name('profile.')->group(function() { $c = 'ProfileController@';
            Route::get('', $c.'main')->name('main');
            Route::patch('', $c.'patch');
        });
        //endregion
        //region Translations
        Route::prefix('translations')->name('translations.')->group(function() { $c = 'TranslationsController@';
            Route::get('{locale}', $c.'main')->name('main');
            Route::get('{locale}/{filename}', $c.'edit')->name('edit');
            Route::patch('{locale}/{filename}', $c.'edit_patch')->name('edit');
        });
        //endregion
        //Home Page Sliders
        Route::prefix('main-slider')->name('main_slider.')->group(function() { $c='MainSliderController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //end sliders
        //region types
        Route::prefix('types')->name('types.')->group(function() { $c='TypesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Categories
        Route::prefix('categories')->name('categories.')->group(function() { $c='CategoriesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        // region Announcements
        Route::prefix('announcements')->name('announcements.')->group(function() { $c='AnnouncementsController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::get('changeStatus/{id}/{status}', $c.'changeStatus')->name('changeStatus');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Filters
        Route::prefix('filters')->name('filters.')->group(function() { $c='FiltersController@';
            Route::get('', $c.'main')->name('main');
            Route::get('priceFilters', $c.'price_filters')->name('list');
            Route::get('add/{price_filter?}/{relation?}', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}/{price_filter?}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Locations
        Route::prefix('locations')->name('locations.')->group(function() { $c='LocationsController@';
            Route::get('main/{parent_id?}/{deep?}', $c.'main')->name('main');
            Route::get('{parent_id?}/{deep?}/add', $c.'add')->name('add');
            Route::put('{parent_id?}/{deep?}/add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::post('changeLocationName', $c.'changeLocationName')->name('changeLocationName');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Estates
        Route::prefix('estates')->name('estates.')->group(function() { $c='EstatesController@';
            Route::get('main/{category?}/{type?}/{code?}', $c.'main')->name('main');
            Route::get('{category?}/{type?}/add', $c.'add')->name('add');

app/Http/Controllers/Admin/GalleriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\NewBuilding;
use App\Models\Service;
use App\Services\Notify\Facades\Notify;
use App\Models\Career;
use App\Models\Gallery;
use App\Models\News;
use App\Models\Page;
use App\Models\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class GalleriesController extends BaseController
{
    //region Private
    private $data = [
        'title'=>'Галерея',
    ];
    private $settings = [
        'thumb_method'=>'fit',
        'thumb_width'=>280,
        'thumb_height'=>175,
        'thumb_upsize'=>false,
        'method'=>'resize',
        'width'=>800,
        'height'=>800,
        'upsize'=>false,
    ];
    private $estate_settings = [
        'thumb_method'=>'fit',
        'thumb_width'=>280,
        'thumb_height'=>175,
        'thumb_upsize'=>false,
        'method'=>'resize',
        'width'=>800,
        'height'=>500,
        'upsize'=>false,
    ];
    private $gallery;
    private $key;

    private function verify($gallery, $key){
        $this->gallery = $this->data['gallery'] = $gallery;
        $this->key = $this->data['key'] = $key;
        $method_name = 'gallery_'.$gallery;
        if (!method_exists($this, $method_name)) abort(404);
        $use_keys = $key===null?false:true;
        $require_keys = (new \ReflectionMethod($this, $method_name))->getNumberOfRequiredParameters()==0?false:true;
        if ($use_keys !== $require_keys)  abort(404);
        if ($key) $this->{$method_name}($key);
        else $this->{$method_name}();
    }

    private function verifyFromRequest($request){
        $gallery = $request->input('gallery');
        $key = $request->input('key');
        if (!$gallery || ($key!==null && !is_id($key))) abort(404);
        $this->verify($gallery, $key);
    }
    private function verifyFromEstateRequest($request){
        $gallery = $request['gallery'];
        $key = $request['key'];
        if (!$gallery || ($key!==null && !is_id($key))) abort(404);
        $this->verify($gallery, $key);
    }
    private function set(array $new_settings){
        $this->settings = array_merge($this->settings, $new_settings);
    }

    public function show($gallery, $key=null) {
        $this->verify($gallery, $key);
        $this->data['images'] = Gallery::adminList($gallery, $key);
        return view('admin.pages.gallery.main', $this->data);
    }

    public function sort(){
        $ids = Gallery::sortable(true);
        if (!$ids) return response()->json(false);
        return response()->json(true);
    }

    public function delete(Request $request){
        $result = ['success'=>false];
        $id = $request->input('item_id');
        if ($id && is_id($id)) {
            $item = Gallery::where('id', $id)->first();
            if ($item && Gallery::deleteItem($item)) $result['success'] = true;
        }
        return response()->json($result);
    }

    public function add(Request $request) {
        $this->verifyFromRequest($request);
        $images = $request->images;
        Validator::make(['images'=>$images], [
            'images'=>'required|array',
            'images.*'=>'image|mimes:png,jpeg,gif'
        ], [
            'required'=>'Выберите изоброжении',
            'array'=>'Выберите изоброжении',
            'image'=>'Формат не поддерживается',
            'mimes'=>'Формат не поддерживается',

        ])->validate();
        if(Gallery::addImages($this->gallery, $this->key, $images, $this->settings)) {
            Notify::success('Изоброжении успешно добавлены');
        }
        else {
            Notify::error('Некаторые изоброжении не добавлены');
        }
        $args = ['gallery'=>$this->gallery];
        if ($this->key) $args['id'] = $this->key;
        return redirect()->route('admin.gallery', $args);
    }
    public function addEstatesGallery($request) {
        $this->verifyFromEstateRequest($request);
        $images = $request['images'];
        Validator::make(['images'=>$images], [
            'images'=>'required|array',
            'images.*'=>'image|mimes:png,jpeg,gif'
        ], [
            'required'=>'Выберите изоброжении',
            'array'=>'Выберите изоброжении',
            'image'=>'Формат не поддерживается',
            'mimes'=>'Формат не поддерживается',

        ])->validate();
        if(Gallery::addImages($this->gallery, $this->key, $images, $this->estate_settings)) {
            Notify::success('Изоброжении успешно добавлены');
        }
        else {
            Notify::error('Некаторые изоброжении не добавлены');
        }
        $args = ['gallery'=>$this->gallery];
        if ($this->key) $args['id'] = $this->key;
        return true;
    }
    public function edit(Request $request) {
        $id = $request->input('item_id');
        $response = ['success'=>false];
        if (is_id($id) && $item = Gallery::where('id', $id)->first()) {
            $values = $request->only('alt', 'title');
            Gallery::updateSeo($item, $values);
            $response['success'] = true;
        }
        return response()->json($response);

    }
    public function poster(Request $request){
        $id = $request->input('item_id');
        $response = ['success'=>false];
        if (is_id($id) && $item = Gallery::where('id', $id)->first()) {
            $values = ['poster'=>$request->poster];
            Gallery::poster($item, $values);
            $response['success'] = true;
        }
        return response()->json($response);
    }
    //endregion

    private function gallery_estates($key){
        $this->data['title'] = 'Галерея';
        $this->data['back_url'] = route('admin.pages.main');
    }

    private function gallery_pages($key) {
        $item = Page::getPage($key);

        $this->data['title'] = 'Галерея страницы "'.$item->a('title').'"';
        $this->data['back_url'] = route('admin.pages.main');
    }

    private function gallery_services_item($key){
        $item = Service::getItem($key);
        $this->data['title'] = 'Галерея услуги "'.$item->a('title').'"';
        $this->data['back_url'] = route('admin.services.main');
    }
    private function gallery_buildings($key){
        $item = NewBuilding::getItem($key);
        $this->data['title'] = 'Галерея новостройки "'.$item->a('title').'"';
        $this->data['back_url'] = route('admin.new_buildings.main');
    }

    private function gallery_news(){
        $this->data['title'] = 'Галерея страницы новостей';
        $this->data['back_url'] = route('admin.pages.main');
    }

    private function gallery_news_item($key){
        $item = News::getItem($key);
        $this->data['title'] = 'Галерея новости "'.$item->a('title').'"';
        $this->data['back_url'] = route('admin.news.main');
    }



}

resources/views/admin/pages/gallery/main.blade.php
@extends('admin.layouts.app')

@section('content')
    @card
        @slot('title') Изоброжении (jpeg, png, gif)@endslot
        <div class="add-new-images">
            @if ($errors->any())
                <div class="py-1 font-weight-bold text-danger text-sm-left text-center">{{ $errors->first() }}</div>
            @endif
            <form action="{{ route('admin.gallery.add') }}" method="post" enctype="multipart/form-data">
                @csrf @method('put')
                <input type="hidden" name="gallery" value="{{ $gallery }}">
                @if($key)
                <input type="hidden" name="key" value="{{ $key }}">
                @endif
                <div class="uploadLine">
                    @file(['name'=>'images[]', 'multiple'=>true])@endfile
                    <div class="ml-sm-2 mt-2 mt-sm-0">
                        <button type="submit" class="btn btn-cyan">Добавить</button>
                    </div>
                </div>
            </form>
        </div>
        @if (count($images))
            <div class="row gallery-row grid-sortable">
                @foreach($images as $image)
                    <div class="col-12 col-sm-4 col-dxl-3 col-xl-2 py-2 item-container" data-id="{{ $image->id }}">
                        <div class="gallery-grid">
                            <img src="{{ $image->image(true) }}" class="gallery-image">
                            <div class="gallery-absolute">
                                <div class="gallery-item-actions">
                                    @if(isset($show_home) && $show_home)
                                        <a href="javascript:void(0)" class="gallery-item-action gallery-item-poster" data-id="{{$image->id}}">{!!  ($image->poster)?'<i class="fas fa-eye" data-poster="true"></i>':'<i class="fas fa-eye-slash" data-poster="false"></i>'!!}</a>
                                    @endif
                                    <a href="javascript:void(0)" class="gallery-item-action gallery-item-edit" data-toggle="modal" data-target="#itemEditModal"><i class="fas fa-pencil-alt"></i></a>
                                    <a href="javascript:void(0)" class="gallery-item-action gallery-item-move"><i class="fas fa-arrows-alt"></i></a>
                                    <a href="javascript:void(0)" class="gallery-item-action" data-toggle="modal" data-target="#itemDeleteModal"><i class="fas fa-trash-alt"></i></a>
                                </div>
                                <div><a href="{{ $image->image() }}" data-fancybox="gallery" class="gallery-item-show"><i class="fas fa-search-plus"></i></a></div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
            @modal(['id'=>'itemDeleteModal', 'centered'=>true, 'loader'=>true,
            'saveBtn'=>'Удалить',
            'saveBtnClass'=>'btn-danger',
            'closeBtn' => 'Отменить',
            'form'=>['id'=>'itemDeleteForm', 'action'=>'javascript:void(0)']])
            @slot('title')Удаление изоброжении@endslot
            <input type="hidden" id="pdf-item-id">
            <p class="font-14">Вы действительно хотите удалить данное изоброжение?</p>
            @endmodal
            @modal(['id'=>'itemEditModal', 'centered'=>true, 'loader'=>true,
            'saveBtn'=>'Редактировать',
            'saveBtnClass'=>'btn-success',
            'closeBtn' => 'Отменить',
            'form'=>['id'=>'itemEditForm', 'action'=>'javascript:void(0)']])
            @slot('title')Редактирование изоброжении@endslot
            <input type="hidden" id="edit-item-id">
            @bylang(['title'=>'SEO', 'id'=>'gallery-bylang'])
            <input type="text" name="alt[{!! $iso !!}]" id="edit-alt-{{ $iso }}" class="form-control" placeholder="Alt">
            <input type="text" name="title[{!! $iso !!}]" id="edit-title-{{ $iso }}" class="form-control mt-2" placeholder="Title">
            @endbylang
            @endmodal
            @push('css')
                @css(aApp('fancybox/fancybox.css'))
            @endpush
            @push('js')
                @js(aApp('fancybox/fancybox.js'))
                <script>
                    var action = "{{ route('admin.gallery.sort') }}";
                    $('.gallery-row').sortable({
                        handle: '.gallery-item-move',
                        update: function(){
                            sortableUpdate($(this), action);
                        }
                    });
                    //region Delete
                    var itemId = $('#pdf-item-id'),
                        blocked = false,
                        modal = $('#itemDeleteModal');
                    loader = modal.find('.modal-loader');
                    function modalError() {
                        loader.removeClass('shown');
                        blocked = false;
                        toastr.error('Возникла проблема!');
                        modal.modal('hide');
                    }
                    modal.on('show.bs.modal', function(e){
                        if (blocked) return false;
                        var button = $(e.relatedTarget),
                            thisItemContainer = button.parents('.item-container');
                        itemId.val(thisItemContainer.data('id'));
                    }).on('hide.bs.modal', function(e){
                        if (blocked) return false;
                    });
                    $('#itemDeleteForm').on('submit', function(){
                        if (blocked) return false;
                        blocked = true;
                        var thisItemId = itemId.val();
                        if (thisItemId && thisItemId.match(/^[1-9][0-9]{0,9}$/)) {
                            loader.addClass('shown');
                            $.ajax({
                                url: '{!! route('admin.gallery.delete') !!}',
                                type: 'post',
                                dataType: 'json',
                                data: {
                                    _token: csrf,
                                    _method: 'delete',
                                    item_id: thisItemId,
                                },
                                error: function(e){
                                    modalError();
                                },
                                success: function(e){
                                    if (e.success) {
                                        loader.removeClass('shown');
                                        blocked = false;
                                        toastr.success('Изоброжение удалено');
                                        modal.modal('hide');
                                        $('.item-container[data-id="'+thisItemId+'"]').fadeOut(function(){
                                            $(this).remove();
                                        });
                                    }
                                    else modalError();
                                }
                            });
                        }
                        else modalError();
                    });
                    //endregion
                    //regionPoster
                    $('.gallery-item-poster').on('click', function() {

                        var thisItemId = $(this).data('id');
                        var poster = '';
                        var elem=$(this);
                        if( $(this).find('i').data('poster') ){
                            poster=0;
                        }
                        else{
                            poster=1;
                        }
                        $.ajax({
                            url: '{!! route('admin.gallery.poster') !!}',
                            type: 'post',
                            dataType: 'json',
                            data: {
                                _token: csrf,
                                _method: 'post',
                                item_id: thisItemId,
                                poster: poster,
                            },
                            error: function (e) {
                                alert('Внутренная ошибка')
                            },
                            success: function (e) {
                                if(elem.find('i').data('poster')){

                                    elem.html('<i class="fas fa-eye-slash" data-poster="false"></i>')
                                }
                                else{
                                    elem.html('<i class="fas fa-eye" data-poster="true"></i>')
                                }
                            }
                        });
                    });
                    //endregion
                    //region SEO
                    var images = {!! $images->mapWithKeys(function($item){
                            return [$item['id'] => ['alt'=>$item->getTranslations('alt'), 'title'=>$item->getTranslations('title')]];
                        })->toJson(JSON_FORCE_OBJECT) !!},
                        isos = {!! json_encode($isos, JSON_UNESCAPED_UNICODE) !!},
                        editModal = $('#itemEditModal'),
                        galleryBylangFirst = $('#gallery-bylang .bylang-nav-tabs .nav-item:first-child>.nav-link');
                    editModal.on('show.bs.modal', function(e){
                        var itemId = $(e.relatedTarget).parents('.item-container').data('id');
                        if (!itemId) {
                            e.preventDefault();
                            return false;
                        }
                        var item = images[itemId];
                        if (!item) {
                            e.preventDefault();
                            return false;
                        }
                        galleryBylangFirst.click();
                        $('#edit-item-id').val(itemId);
                        for (var i in isos) {
                            var iso = isos[i];
                            $('#edit-alt-'+iso).val(item.alt[iso] || null);
                            $('#edit-title-'+iso).val(item.title[iso] || null);
                        }
                    });
                    var editModalError = function(loader){
                        loader.removeClass('shown');
                        blocked = false;
                        toastr.error('Возникла проблема!');
                        editModal.modal('hide');
                    };
                    $('#itemEditForm').on('submit', function(){
                        if (blocked) return false;
                        blocked = true;
                        var loader = editModal.find('.modal-loader');
                        var thisItemId = $(this).find('#edit-item-id').val();
                        if (thisItemId && thisItemId.match(/^[1-9][0-9]{0,9}$/)) {
                            var alts = {},
                                titles = {};
                            for (var i in isos) {
                                var iso = isos[i];
                                alts[iso] = $.trim($('#edit-alt-'+iso).val());
                                titles[iso] = $.trim($('#edit-title-'+iso).val());
                            }
                            loader.addClass('shown');
                            $.ajax({
                                url: '{!! route('admin.gallery.edit') !!}',
                                type: 'post',
                                dataType: 'json',
                                data: {
                                    _token: csrf,
                                    _method: 'patch',
                                    item_id: thisItemId,
                                    alt: alts,
                                    title: titles
                                },
                                error: function(e){
                                    console.error(e.responseText);
                                    editModalError(loader);
                                },
                                success: function(e){
                                    if (e.success) {
                                        loader.removeClass('shown');
                                        blocked = false;
                                        toastr.success('Изменения сохранены.');
                                        editModal.modal('hide');
                                        images[thisItemId] = {
                                            alt: alts,
                                            title: titles
                                        }
                                    }
                                    else editModalError(loader);
                                }
                            });
                        }
                        else editModalError(loader);
                    });
                    //endregion
                </script>
            @endpush
        @endif
    @endcard
@endsection