routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Services\LanguageManager\Facades\LanguageManager;

//region Admin
//region Login
Route::group(['prefix' => config('admin.prefix'), 'middleware'=>'notAdmin'], function (){
    Route::get('login', 'Admin\AuthController@login')->name('admin.login');
    Route::post('login', 'Admin\AuthController@attemptLogin');
    Route::get('password/reset', 'Admin\AuthController@reset')->name('admin.password.reset');
    Route::post('password/reset', 'Admin\AuthController@attemptReset');
    Route::get('password/recover/{email}/{token}', 'Admin\AuthController@recover')->where(['email'=>'[^\/]+', 'token'=>'[^\/]+'])->name('admin.password.recover');
    Route::post('password/recover/{email}/{token}', 'Admin\AuthController@attemptRecover')->where(['email'=>'[^\/]+', 'token'=>'[^\/]+']);
});
//endregion
Route::get('verify-email/{email}/{token}', 'Site\Auth\RegisterController@verifyEmail')->name('verify_email');

Route::middleware('setLocale')->group(function(){
    Route::post('send-mail', 'Site\AppController@sendMail')->name('contacts.send_mail');
});
Route::group(['prefix' => config('admin.prefix'), 'middleware' => 'admin'], function () {
    //region CKFinder
    Route::any('file_browser/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
    Route::any('file_browser/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');
    //endregion
    Route::name('admin.')->namespace('Admin')->group(function(){
        //region Logout
        Route::post('logout', 'AuthController@logout')->name('logout');
        //endregion
        //region Home Page Redirect
        Route::get('/', 'AuthController@redirectIfAuthenticated');
        //endregion
        //region Dashboard
        Route::get('dashboard', 'DashboardController@main')->name('dashboard');
        //endregion
        //region Languages
        Route::prefix('languages')->name('languages.')->group(function() { $c='LanguagesController@';
            Route::get('', $c.'main')->name('main');
            Route::patch('', $c.'editLanguage');
        });
        //endregion
        //region Pages
        Route::prefix('pages')->name('pages.')->group(function() { $c='PagesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'addPage')->name('add');
            Route::put('add', $c.'addPage_put');
            Route::get('edit/{id}', $c.'editPage')->name('edit');
            Route::patch('edit/{id}', $c.'editPage_patch');
            Route::delete('delete', $c.'deletePage_delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Pages
        Route::prefix('new_buildings')->name('new_buildings.')->group(function() { $c='NewBuildingController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
            Route::post('search', $c.'search_estate')->middleware('ajax')->name('search_estate');
        });
        //endregion
        //region Banners
        Route::match(['get', 'post'], 'banners/{page}', 'BannersController@renderPage')->name('banners');

        Route::prefix('gallery')->group(function(){ $c='GalleriesController@';
            Route::get('{gallery}/{id?}{key?}', $c.'show')->name('gallery');
            Route::put('add', $c.'add')->name('gallery.add');
            Route::patch('edit', $c.'edit')->middleware('ajax')->name('gallery.edit');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('gallery.sort');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('gallery.delete');
            Route::post('poster', $c.'poster')->middleware('ajax')->name('gallery.poster');
        });
        //endregion
        //region Users
        Route::prefix('users')->name('users.')->group(function(){ $c='UsersController@';
            Route::get('', $c.'main')->name('main');
            Route::get('{id}', $c.'view')->name('view');
            Route::get('list/{user_type}', $c.'list')->name('list');
            Route::patch('toggle-active', $c.'toggleActive')->name('toggleActive');
        });
        //endregion
        //region Video Galleries
        Route::prefix('video-gallery')->group(function(){ $c='VideoGalleriesController@';
            Route::get('{gallery}/{id?}', $c.'show')->name('video_gallery');
            Route::get('{gallery}/add/{id?}', $c.'add')->name('video_gallery.add');
            Route::put('{gallery}/add/{id?}', $c.'add_put');
            Route::get('{id}/edit', $c.'edit')->name('video_gallery.edit');
            Route::patch('{id}/edit', $c.'edit_patch');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('video_gallery.sort');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('video_gallery.delete');
        });
        //endregion
        //region Profile
        Route::prefix('profile')->name('profile.')->group(function() { $c = 'ProfileController@';
            Route::get('', $c.'main')->name('main');
            Route::patch('', $c.'patch');
        });
        //endregion
        //region Translations
        Route::prefix('translations')->name('translations.')->group(function() { $c = 'TranslationsController@';
            Route::get('{locale}', $c.'main')->name('main');
            Route::get('{locale}/{filename}', $c.'edit')->name('edit');
            Route::patch('{locale}/{filename}', $c.'edit_patch')->name('edit');
        });
        //endregion
        //Home Page Sliders
        Route::prefix('main-slider')->name('main_slider.')->group(function() { $c='MainSliderController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //end sliders
        //region types
        Route::prefix('types')->name('types.')->group(function() { $c='TypesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Categories
        Route::prefix('categories')->name('categories.')->group(function() { $c='CategoriesController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        // region Announcements
        Route::prefix('announcements')->name('announcements.')->group(function() { $c='AnnouncementsController@';
            Route::get('', $c.'main')->name('main');
            Route::get('add', $c.'add')->name('add');
            Route::get('changeStatus/{id}/{status}', $c.'changeStatus')->name('changeStatus');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Filters
        Route::prefix('filters')->name('filters.')->group(function() { $c='FiltersController@';
            Route::get('', $c.'main')->name('main');
            Route::get('priceFilters', $c.'price_filters')->name('list');
            Route::get('add/{price_filter?}/{relation?}', $c.'add')->name('add');
            Route::put('add', $c.'add_put');
            Route::get('edit/{id}/{price_filter?}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Locations
        Route::prefix('locations')->name('locations.')->group(function() { $c='LocationsController@';
            Route::get('main/{parent_id?}/{deep?}', $c.'main')->name('main');
            Route::get('{parent_id?}/{deep?}/add', $c.'add')->name('add');
            Route::put('{parent_id?}/{deep?}/add', $c.'add_put');
            Route::get('edit/{id}', $c.'edit')->name('edit');
            Route::patch('edit/{id}', $c.'edit_patch');
            Route::post('changeLocationName', $c.'changeLocationName')->name('changeLocationName');
            Route::delete('delete', $c.'delete')->middleware('ajax')->name('delete');
            Route::patch('sort', $c.'sort')->middleware('ajax')->name('sort');
        });
        //endregion
        //region Estates

app/Models/VideoGallery.php
<?php

namespace App\Models;

use App\Http\Traits\Sortable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class VideoGallery extends Model
{
    use Sortable;

    public $timestamps = false;

    public static function adminList($gallery, $key=null){
        return self::where(['gallery'=>$gallery, 'key'=>$key])->sort()->get();
    }

    public static function action($model, $inputs) {
        if (empty($model)) {
            $model = new self;
            $model['gallery'] = $inputs['gallery'];
            $model['key'] = $inputs['key'];
        }
        $model['active'] = (int) !empty($inputs['active']);
        $model['video'] = preg_match('%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i', $inputs['video'], $video)?$video[1]:$inputs['video'];

        return $model->save();
    }

    public static function getItem($id) {
        return self::findOrFail($id);
    }

    public static function deleteItem($model){
        return $model->delete();
    }

    public static function get($gallery, $key=null){
        return self::select('video')->where(['gallery'=>$gallery, 'key'=>$key, 'active'=>1])->sort()->get();
    }

    public static function clear($gallery, $key=null){
        return self::where(['gallery'=>$gallery, 'key'=>$key])->delete();
    }

}

app/Http/Controllers/Admin/VideoGalleriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\News;
use App\Models\Page;
use App\Models\VideoGallery;
use App\Services\Notify\Facades\Notify;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class VideoGalleriesController extends BaseController
{
    //region Private
    private $data = [
        'title'=>'Галерея',
    ];
    private $gallery;
    private $key;
    private function verify($gallery, $key){
        $this->gallery = $this->data['gallery'] = $gallery;
        $this->key = $this->data['key'] = $key;
        $method_name = 'gallery_'.$gallery;
        if (!method_exists($this, $method_name)) abort(404);
        $use_keys = $key===null?false:true;
        $require_keys = (new \ReflectionMethod($this, $method_name))->getNumberOfRequiredParameters()==0?false:true;
        if ($use_keys !== $require_keys) abort(404);
        if ($key) $this->{$method_name}($key);
        else $this->{$method_name}();
    }
    public function show($gallery, $key=null) {
        $this->verify($gallery, $key);
        $this->data['items'] = VideoGallery::adminList($gallery, $key);
        return view('admin.pages.video_gallery.main', $this->data);
    }
    public function add($gallery, $key=null) {
        $this->verify($gallery, $key);
        $this->data['title'] .= ' | добавление видео';
        $this->data['edit'] = false;
        $this->data['back_url'] = route('admin.video_gallery', ['gallery'=>$gallery, 'id'=>$key]);
        return view('admin.pages.video_gallery.form', $this->data);
    }
    public function add_put(Request $request, $gallery, $key=null) {
        $this->verify($gallery, $key);
        $inputs = $request->all();
        $this->validator($inputs)->validate();
        $inputs['gallery'] = $gallery;
        $inputs['key'] = $key;
        if(VideoGallery::action(null, $inputs)) {
            Notify::success('Видео успешно добавлено.');
            return redirect()->route('admin.video_gallery', ['gallery'=>$gallery, 'id'=>$key]);
        }
        else {
            Notify::get('error_occurred');
            return redirect()->back()->withInput();
        }
    }
    public function edit($id) {
        $item = $this->data['item'] = VideoGallery::getItem($id);
        $this->verify($item->gallery, $item->key);
        $this->data['title'] .= ' | редактирование видео';
        $this->data['edit'] = true;
        $this->data['back_url'] = route('admin.video_gallery', ['gallery'=>$item->gallery, 'id'=>$item->key]);
        return view('admin.pages.video_gallery.form', $this->data);
    }
    public function edit_patch(Request $request, $id) {
        $item = VideoGallery::getItem($id);
        $inputs = $request->all();
        $this->validator($inputs)->validate();
        if(VideoGallery::action($item, $inputs)) {
            Notify::success('Видео успешно редактировано.');
            return redirect()->route('admin.video_gallery.edit', ['id'=>$item->id]);
        }
        else {
            Notify::get('error_occurred');
            return redirect()->back()->withInput();
        }
    }
    public function sort(){ return VideoGallery::sortable(); }
    public function delete(Request $request) {
        $result = ['success'=>false];
        $id = $request->input('item_id');
        if ($id && is_id($id)) {
            $page = VideoGallery::where('id', $id)->first();
            if ($page && VideoGallery::deleteItem($page)) $result['success'] = true;
        }
        return response()->json($result);
    }
    private function validator($inputs) {
        return Validator::make($inputs, [
            'video' => 'required|string',
        ], [
            'video.required'=>'Введите ссылку видео.',
            'video.string'=>'Введите ссылку видео.'
        ]);
    }
    //endregion

    private function gallery_about(){
        $this->data['title'] = 'Видеогалерея страницы о компании';
        $this->data['back_url'] = route('admin.pages.main');
    }

    private function gallery_pages($key) {
        $item = Page::getPage($key);
        $this->data['title'] = 'Видеогалерея страницы "'.$item->a('title').'"';
        $this->data['back_url'] = route('admin.pages.main');
    }

    private function gallery_news(){
        $this->data['title'] = 'Видеогалерея страницы новостей';
        $this->data['back_url'] = route('admin.pages.main');
    }

    private function gallery_news_item($key){
        $item = News::getItem($key);
        $this->data['title'] = 'Видеогалерея новости "'.$item->a('title').'"';
        $this->data['back_url'] = route('admin.news.main');
    }

}

resources/views/admin/pages/video_gallery/form.blade.php
@extends('admin.layouts.app')
@section('content')
<form action="{{ $edit?route('admin.video_gallery.edit', ['id'=>$item->id]):route('admin.video_gallery.add', ['gallery'=>$gallery, 'id'=>$key]) }}" method="post">
    @csrf @method($edit?'patch':'put')
    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif
    <div class="row">
        <div class="col-12 col-lg-6">
            @card(['title'=>'Видео'])
            <input type="text" name="video" class="form-control" placeholder="Ссылка/ID видео Youtube" value="{{ old('video', $item->video??null) }}">
            @labelauty(['id'=>'active', 'label'=>'Неактивно|Активно', 'class'=>'mt-2 mb-0', 'checked'=>oldCheck('active', ($edit && empty($item->active))?false:true)])@endlabelauty
            @endcard
        </div>
        @if($edit && $item->video)
            <div class="col-12 col-lg-6">
                <iframe style="width:100%; height:300px;" src="{{ url('https://www.youtube.com/embed/'.$item->video) }}" frameborder="0" allow="autoplay;" allowfullscreen></iframe>
            </div>
        @endif
        <div class="col-12 save-btn-fixed"><button type="submit"></button></div>
    </div>
</form>
@endsection

resources/views/admin/pages/video_gallery/main.blade.php
@extends('admin.layouts.app')
@section('titleSuffix')| <a href="{!! route('admin.video_gallery.add', ['gallery'=>$gallery, 'id'=>$key]) !!}" class="text-cyan"><i class="mdi mdi-plus-box"></i> добавить</a>@endsection
@section('content')
    @if(count($items))
        <div class="card">
            <div class="table-responsive">
                <table class="table table-striped m-b-0 columns-middle">
                    <thead>
                    <tr>
                        <th>Видео</th>
                        <th>Статус</th>
                        <th>Действие</th>
                    </tr>
                    </thead>
                    <tbody class="table-sortable" data-action="{{ route('admin.video_gallery.sort') }}">
                    @foreach($items as $item)
                        <tr class="item-row" data-id="{!! $item->id !!}">
                            <td class="item-title">
                                <a href="{{ url('https://www.youtube.com/watch?v='.$item->video) }}" target="_blank">
                                    <img src="{{ asset('https://i.ytimg.com/vi/'.$item->video.'/hqdefault.jpg') }}" alt="" style="width:150px; height:auto; border:1px solid #cccccc;">
                                </a>
                            </td>
                            @if($item->active)
                                <td class="text-success">Активно</td>
                            @else
                                <td class="text-danger">Неактивно</td>
                            @endif
                            <td>
                                <a href="{{ route('admin.video_gallery.edit', ['id'=>$item->id]) }}" {!! tooltip('Редактировать') !!} class="icon-btn edit"></a>
                                <span class="d-inline-block" data-toggle="modal" data-target="#itemDeleteModal"><a href="javascript:void(0)" class="icon-btn delete" {!! tooltip('Удалить') !!}></a></span>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @else
        <h4 class="text-danger">@lang('admin/all.empty')</h4>
    @endif
    @modal(['id'=>'itemDeleteModal', 'centered'=>true, 'loader'=>true,
        'saveBtn'=>'Удалить',
        'saveBtnClass'=>'btn-danger',
        'closeBtn' => 'Отменить',
        'form'=>['id'=>'itemDeleteForm', 'action'=>'javascript:void(0)']])
    @slot('title')Удаление видео@endslot
    <input type="hidden" id="pdf-item-id">
    <p class="font-14">Вы действительно хотите удалить данное видео?</p>
    @endmodal
@endsection
@push('css')
@endpush
@push('js')
    <script>
        var itemId = $('#pdf-item-id'),
            blocked = false,
            modal = $('#itemDeleteModal');
        loader = modal.find('.modal-loader');
        function modalError() {
            loader.removeClass('shown');
            blocked = false;
            toastr.error('Возникла проблема!');
            modal.modal('hide');
        }
        modal.on('show.bs.modal', function(e){
            if (blocked) return false;
            var $this = $(this),
                button = $(e.relatedTarget),
                thisItemRow = button.parents('.item-row');
            itemId.val(thisItemRow.data('id'));
        }).on('hide.bs.modal', function(e){
            if (blocked) return false;
        });
        $('#itemDeleteForm').on('submit', function(){
            if (blocked) return false;
            blocked = true;
            var thisItemId = itemId.val();
            if (thisItemId && thisItemId.match(/^[1-9][0-9]{0,9}$/)) {
                loader.addClass('shown');
                $.ajax({
                    url: '{!! route('admin.video_gallery.delete') !!}',
                    type: 'post',
                    dataType: 'json',
                    data: {
                        _token: csrf,
                        _method: 'delete',
                        item_id: thisItemId,
                    },
                    error: function(e){
                        modalError();
                        console.log(e.responseText);
                    },
                    success: function(e){
                        if (e.success) {
                            loader.removeClass('shown');
                            blocked = false;
                            toastr.success('Видео удалено');
                            modal.modal('hide');
                            $('.item-row[data-id="'+thisItemId+'"]').fadeOut(function(){
                                $(this).remove();
                            });
                        }
                        else modalError();
                    }
                });
            }
            else modalError();
        });
    </script>
@endpush